# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 81, 31))
        self.label.setObjectName("label")
        self.cboxFormato = QtWidgets.QComboBox(self.centralwidget)
        self.cboxFormato.setGeometry(QtCore.QRect(70, 90, 121, 21))
        self.cboxFormato.setObjectName("cboxFormato")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 51, 21))
        self.label_2.setObjectName("label_2")
        self.edtURL = QtWidgets.QLineEdit(self.centralwidget)
        self.edtURL.setGeometry(QtCore.QRect(90, 40, 451, 21))
        self.edtURL.setObjectName("edtURL")
        self.btnLimpar = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimpar.setGeometry(QtCore.QRect(550, 40, 75, 23))
        self.btnLimpar.setObjectName("btnLimpar")
        self.labelDestino = QtWidgets.QLabel(self.centralwidget)
        self.labelDestino.setGeometry(QtCore.QRect(20, 120, 421, 20))
        self.labelDestino.setObjectName("labelDestino")
        self.btnAbrir = QtWidgets.QPushButton(self.centralwidget)
        self.btnAbrir.setGeometry(QtCore.QRect(550, 120, 75, 23))
        self.btnAbrir.setObjectName("btnAbrir")
        self.btnEscolher = QtWidgets.QPushButton(self.centralwidget)
        self.btnEscolher.setGeometry(QtCore.QRect(450, 120, 81, 23))
        self.btnEscolher.setObjectName("btnEscolher")
        self.btnBaixar = QtWidgets.QPushButton(self.centralwidget)
        self.btnBaixar.setGeometry(QtCore.QRect(270, 150, 111, 41))
        self.btnBaixar.setObjectName("btnBaixar")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 241, 621, 171))
        self.listView.setObjectName("listView")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 210, 551, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "URL do vídeo:"))
        self.label_2.setText(_translate("MainWindow", "Formato:"))
        self.btnLimpar.setText(_translate("MainWindow", "Limpar URL"))
        self.labelDestino.setText(_translate("MainWindow", "TextLabel"))
        self.btnAbrir.setText(_translate("MainWindow", "Abrir pasta"))
        self.btnEscolher.setText(_translate("MainWindow", "Escolher pasta"))
        self.btnBaixar.setText(_translate("MainWindow", "Baixar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
